### ISSUE TITLE
Inconsistent "state" suffix across states in NIGERIA

### ISSUE THREAD

**Issue by johnexzy** [MartinsOnuoha/countriesNowAPI#112]
Although several issues have been fixed around this niche, I think Lagos should have a ``state`` suffix like other states in Nigeria to please data consistency.

The entry point to easily solving this should be on the datastore [here](https://github.com/MartinsOnuoha/countriesNowAPI/blob/45d7d60eacb4ccebf8214c3eb87027a44d45988f/model/countriesAndState.js#L16324)

**Comment by MartinsOnuoha** [comment]
@johnexzy thanks for reporting this, we have an open MR to fix this. feel free to review
