### ISSUE TITLE
Duplicate City Names

### ISSUE THREAD

**Issue by knityanand** [MartinsOnuoha/countriesNowAPI#114]
Cheers for a very useful set of API's.

However, There are some cities which are getting duplicated. e.g.

For the below API 
https://countriesnow.space/swagger-docs/#/Cities/post_state_cities with the below data 
{
  "country": "India",
  "state": "Telangana"
}
 
And the result, I see that some cities are getting duplicated e.g.
 
"Hyderabad",
"Hyderābād", 

One more e.g for the same API with the below input data 
{
  "country": "India",
  "state": "Andhra Pradesh"
}

You get the following duplicates in the output.
"Guntur",
"Guntūr",

**Comment by MartinsOnuoha** [comment]
Hi @knityanand Are these all of the duplicates you found? if so would you like to open a MR to fix this issue?

**Comment by knityanand** [comment]
Hello @MartinsOnuoha , these were just a sample set of issues. I have not checked all of them..

**Comment by MartinsOnuoha** [comment]
@knityanand thanks for reporting this, we now have an open MR to fix this
