### ISSUE TITLE
Duplicate Country Name

### ISSUE THREAD

**Issue by Danushka96** [MartinsOnuoha/countriesNowAPI#120]
"Jordan" country is duplicated in the query results

**Comment by MartinsOnuoha** [comment]
Hi @Danushka96 can you point out which endpoint returns this duplicates?

**Comment by annadarina** [comment]
Hi @MartinsOnuoha it's https://countriesnow.space/api/v0.1/countries.

Also, I noticed that 'Myanmar' country is duplicated as well.
