### ISSUE TITLE
Missing Cities in France

### ISSUE THREAD

**Issue by YanisGANGNANT** [MartinsOnuoha/countriesNowAPI#138]
Hello,
So, I'm french, and I'm using your API for a school projects, and I wanted to test my work with the cities near me, and I've found multiple cities missing, in France. I don't got the list of all of them, but I know a few of them, like "Méziré", "Morvillars", "Montbéliard".
Is there any way to update the cities in France pls ?
Thanks for your incredible work :)

**Comment by MartinsOnuoha** [comment]
Hi @Pastis444 
Thanks for reporting this. Yes there is, can you provide some more info about these missing cities. 
Like the state they belong to. That would be helpful.

**Comment by Pastis444** [comment]
The cities I've listed are in a state called "Bourgogne-Franche-Comté", but it might have some more cities that aren't listed. I will try to make a python script to scrap all cities in france with there state, population, and all datas related that you provide with your api, and I'll make a pull request. It might take some times as I'm really busy with the University, but I'll try to do my best ASAP.
