### ISSUE TITLE
Missing Basel-Stadt

### ISSUE THREAD

**Issue by clauderobi** [MartinsOnuoha/countriesNowAPI#140]
Hi,

Nice work!!

Last year you fix missing Basel as a city. But Basel-Stadt is also a Kanton. So the list of Kanton (oe states), which there are 26 in Switzerland, only lists 25 of them and miss Basel-Stadt.

**Comment by MartinsOnuoha** [comment]
Hi @clauderobi thanks for reporting this, I'll open a fix to this.
