### ISSUE TITLE
Inconsistent State suffix: error fetching cities in lagos state

### ISSUE THREAD

**Issue by johnexzy** [MartinsOnuoha/countriesNowAPI#143]
Hi @MartinsOnuoha 

I guess i am known for these kinda issues by now😅, saw this one while watching hotjar's recordings,

After reviewing Issue #136 and its fix, we also need to do same with the StateCity by appending "state" to Lagos in ``model/countriesStateCity.js`` Line `486046` on the datastore. 

## More context
``api/v0.1/countries/state/cities/q?country=Nigeria&state=kaduna%20state`` 200 OK
``api/v0.1/countries/state/cities/q?country=Nigeria&state=niger%20state``  200 OK
``api/v0.1/countries/state/cities/q?country=Nigeria&state=lagos%20state`` 404 Not Found

**Comment by MartinsOnuoha** [comment]
Thanks for spotting this out again! ❤️
