### ISSUE TITLE
Missing city for Lagos State, Nigeria

### ISSUE THREAD

**Issue by wizarphics** [MartinsOnuoha/countriesNowAPI#148]
`Agege`  is  missing when fetching the cities for state `Lagos` in country `Nigeria`

**Comment by MartinsOnuoha** [comment]
Hi @Wizarphics , as far as I know, Agege is only an LGA and not necessarily a city in Lagos. Do you have any documentation showing Agege as a city? if so, please share then we can talk about fixing it.

**Comment by Wizarphics** [comment]
Ok I don't have any documents that backs it I just feel like the cities returned looks more like the Lagos Divisions but then I noticed it was more than five so I thought Agege should be included but when i check with Google I got a longer list but Agege was not included.

**Comment by MartinsOnuoha** [comment]
So we can close this issue in that case @wizarphics
