### ISSUE TITLE
Not able to get country, capital and flag using the filter

### ISSUE THREAD

**Issue by SiddharthRana** [MartinsOnuoha/countriesNowAPI#157]
How can we get country name, capital and flag in the response. capital query is not working on filter. Could you please help?

**Comment by MartinsOnuoha** [comment]
Can you point what endpoint you're referring to?

**Comment by SiddharthRana** [comment]
`https://countriesnow.space/api/v0.1/countries/info?returns=name,flag,capital`

I cant get the capital using api like this. I want to get only 3 informations i.e. name, flag and capital. Can i do that?

**Comment by MartinsOnuoha** [comment]
Hi @SiddharthRana, You can already get `name` and `flag` by making a get request to the endpoint and passing both params. However, we didn't have support to query capital, but I have opened a merge request to fix that. You should now be able to get the capital by also passing the `capital` query param.

 `/info?returns=name,flag,capital`
