### ISSUE TITLE
not able to get some countries city

### ISSUE THREAD

**Issue by prdraco** [MartinsOnuoha/countriesNowAPI#158]
Hi!

Need help to get couple of countries cities. How can type in the get request if the country comes 2 or more seperate words for example:
https://countriesnow.space/api/v0.1/countries/population/cities/filter/q?limit=800000&order=asc&orderBy=name&country=

and the country is United Kingdom as you know I'll get an error code with this request : 
https://countriesnow.space/api/v0.1/countries/population/cities/filter/q?limit=800000&order=
asc&orderBy=name&country=united kingdom

I tried many other options like united&kingdom, or united&20kingdom, or united-kingdom, or united_kingdom
could be better with iso3 code.
thanks, Robert

**Comment by MartinsOnuoha** [comment]
Hi @prdraco, thanks for reporting this. I have create a fix.
please use a `POST` request instead of a `GET` request with your body param of this format:

```json
{
	"limit": 10,
	"order": "asc",
	"orderBy": "name",
	"country": "united states"
}
```
