### ISSUE TITLE
Afghanistan flag

### ISSUE THREAD

**Issue by Huzefa1122** [MartinsOnuoha/countriesNowAPI#170]
So i think the wikipedia has moved the svg file and flags url is incorrect. 
I found this one https://upload.wikimedia.org/wikipedia/commons/5/5f/Flag_of_Afghanistan_%28Colored_Emblem%29.svg and this works

**Comment by MartinsOnuoha** [comment]
Hi @Huzefa1122 thanks for catching this, would you like to update the URLs in a new MR?

**Comment by Huzefa1122** [comment]
😃 Sure
