### ISSUE TITLE
Missing states for Bahamas

### ISSUE THREAD

**Issue by namln-hust** [MartinsOnuoha/countriesNowAPI#177]
I encountered an error with the API today

- Request
    `curl --location 'https://countriesnow.space/api/v0.1/countries/states' \
    --header 'Content-Type: application/json' \
    --data '{
        "country": "Bahamas"
    }'`

- Response
    `{"error":true,"msg":"country not found"}`

Is there anything wrong with my API call or is it an issue with the API data?

**Comment by namln-hust** [comment]
I notice that the country name returned from API `**Get countries and ISO2&3 Codes**` for Bahamas is `**Bahamas**`, while the actual name that is valid in API `**Get single country and its states**` and `**Get all countries and their states**` should be `**Bahamas The**`. Details in [This API docs](https://documenter.getpostman.com/view/1134062/T1LJjU52)

This seems to be a conflict in data among the APIs.

Can you please fix this?

**Comment by MartinsOnuoha** [comment]
Hi @namln-hust yes this is a bug, Ideally the name should be "Bahamas" uniformly.

**Comment by MartinsOnuoha** [comment]
@namln-hust sorry, this took a while but it should be resolved now.
