### ISSUE TITLE
Almost all "States" in the United Kingdom returns an empty City

### ISSUE THREAD

**Issue by Philx62** [MartinsOnuoha/countriesNowAPI#192]
Hello, tried getting list of cities from the UK but most returns an empty list.

this is my request parameter:

https://countriesnow.space/api/v0.1/countries/state/cities/q?country=United%20Kingdom&state=Aberdeen

and this is my returned value :

{
    "error": false,
    "msg": "cities in state Aberdeen of country United Kingdom retrieved",
    "data": []
}

II initially thought the issue might be with a specific state (e.g., Aberdeen), but I tested about 70% of UK states and got the same result. the only working states i could find was England, Wales and Scotland.

**Comment by MartinsOnuoha** [comment]
Hi @Philx62 we had a similar thread opened here
https://github.com/MartinsOnuoha/countriesNowAPI/issues/182
Do you think you could follow up on this thread?

**Comment by MartinsOnuoha** [comment]
@Philx62 do you expect this structure? 

> The United Kingdom (UK) does not have "states" like the United States. Instead, it is divided into four constituent countries, each with its own system of governance and regional identities. These are:
> 
> England
> Scotland
> Wales
> Northern Ireland
> Each country is further divided into smaller administrative regions:
> 
> England: Includes counties such as Yorkshire, Cornwall, and Kent.
> Scotland: Divided into council areas like Glasgow City and Highland.
> Wales: Divided into principal areas like Cardiff and Swansea.
> Northern Ireland: Comprises districts like Belfast and Derry City and Strabane.

**Comment by Philx62** [comment]
Hi @MartinsOnuoha,
yes this is the structure i expected.
but using the current setup if Northern Ireland is selected as a state to display a list of cities there is no data for these cities.

**Comment by MartinsOnuoha** [comment]
Okay I understand that's the current experience, but I would be making updates to return the districts instead of empty data
@Philx62

**Comment by Adebesin-Cell** [comment]
> Okay I understand that's the current experience, but I would be making updates to return the districts instead of empty data @Philx62

That'll be cool! Thank you. I thought something was wrong with my approach when cities weren't returned 😅.

**Comment by Adebesin-Cell** [comment]
<img width="892" alt="Screenshot 2024-11-18 at 7 19 35 AM" src="https://github.com/user-attachments/assets/21420364-069a-4497-99a3-b869dadcc66c">

If it helps it seems when I select a state to fetch cities (I suppose now it'll return districts) in uk, it returns ``State not found``, perhaps it can also be resolved, thanks! 👍

**Comment by MartinsOnuoha** [comment]
Thanks Adebesin, I'll resolve this alongside.

**Comment by Adebesin-Cell** [comment]
> Thanks Adebesin, I'll resolve this alongside.

Cool! Thanks, great work 👏

**Comment by Philx62** [comment]
Hey @MartinsOnuoha  how's the returns for the cities in the UK going? any roadblocks?

**Comment by MartinsOnuoha** [comment]
@Philx62 there's an open MR now, feel free to have a look before it's merged.
https://github.com/MartinsOnuoha/countriesNowAPI/pull/193
