### ISSUE TITLE
Public API - Swagger link down

### ISSUE THREAD

**Issue by boxxmon** [MartinsOnuoha/countriesNowAPI#201]
Public API appears to be offline:
https://countriesnow.space/swagger-docs

**Comment by everestster** [comment]
Not just swagger. The whole API is doen. I'm getting this error when I tried to send request via post man to https://countriesnow.space/api/v0.1/countries/states

`<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>Heroku | Application Error</title>
    <style media="screen">
        html,
        body,
        iframe {
            margin: 0;
            padding: 0;
        }

        html,
        body {
            height: 100%;
            overflow: hidden;
        }

        iframe {
            width: 100%;
            height: 100%;
            border: 0;
        }
    </style>
</head>

<body>
    <iframe src="//www.herokucdn.com/error-pages/no-such-app.html"></iframe>
</body>

</html>`

**Comment by MartinsOnuoha** [comment]
Hello, apologies for the downtime, we are back online 🚀 
we were late on our service payment. 
![CleanShot 2024-12-23 at 9  11 24@2x](https://github.com/user-attachments/assets/8ce8972d-e08d-4786-a2b4-b7a4c92bcb92)

Here's a link if you'd like to [support](buymeacoffee.com/martinsvicf). ❤️
