### ISSUE TITLE
Svg images returns 404.

### ISSUE THREAD

**Issue by MartinsOnuoha** [MartinsOnuoha/countriesNowAPI#24]
- For the countries and flag images endpoint, some of the images return 404
   - Flag of Honduras
   - Flag of British Indian Ocean Territory
   - Flag of Guadeloupe
   - Flag of Heard Island and McDonald Islands
   - Flag of Honduras
   - Flag of Martinique
   - Flag of New Caledonia
   - Flag of Swaziland

**Comment by MartinsOnuoha** [comment]
To resolve this issue, we'd need to get the updated URL for these flags images from Wikipedia and replace them with the existing URL for the `/countries/flags` JSON data.

**Comment by Mr-emeka** [comment]
Would definitely Love to work on this.

**Comment by MartinsOnuoha** [comment]
@Mr-emeka Great!, be sure to check out the contribution guide. [Here](https://github.com/MartinsOnuoha/countriesNowAPI/blob/master/docs/contributing.md)

**Comment by MartinsOnuoha** [comment]
@

> * For the countries and flag images endpoint, some of the images return 404
>   
>   * Flag of Honduras
>   * Flag of British Indian Ocean Territory
>   * Flag of Guadeloupe
>   * Flag of Heard Island and McDonald Islands
>   * Flag of Honduras
>   * Flag of Martinique
>   * Flag of New Caledonia
>   * Flag of Swaziland

@Mr-emeka So I looked up Heard Island and McDonald Islands and the location has been Uninhabited since 2011 due to its heavy volcanic activities and barren Antarctic islands thus they do not have flags. So it's okay to omit them
