### ISSUE TITLE
Country: "Anguilla" Not Found 

### ISSUE THREAD

**Issue by MartinsOnuoha** [MartinsOnuoha/countriesNowAPI#26]
- querying the `/cities` endpoint, with `{ country: "Anguilla" }` returns `404`
- Looking through the response from the `/cities` endpoint, the country "Anguilla" doesn't exist
- This is basically another missing data issue
- This can be resolved if we have all the cities under Anguilla
- Ref: http://www.fallingrain.com/world/AV/

**Comment by MartinsOnuoha** [comment]
In the spirit of Hacktoberfest kicking off tomorrow, I'm adding the "Hacktoberfest" label so participants can contribute to CountriesNow and bag Hacktoberfest swags. 🎉

**Comment by FladioArmandika** [comment]
Can I contribute here??
