### ISSUE TITLE
Add endpoint to get a random country on request.

### ISSUE THREAD

**Issue by MartinsOnuoha** [MartinsOnuoha/countriesNowAPI#36]
## Requirement
- add a new `/random` endpoint that returns a random country object on request.
- It is not yet clear what details of the country would be needed, but the basics for now.
   - name
   - iso2/3
   - dial code

**Comment by deepank120896** [comment]
@MartinsOnuoha I would like to work on this

**Comment by ryzbaka** [comment]
I can work on this feature.

**Comment by ryzbaka** [comment]
I have created a PR in response to this issue : https://github.com/MartinsOnuoha/countriesNowAPI/pull/37

**Comment by MartinsOnuoha** [comment]
@deepank120896 @ryzbaka 
Please be sure to go through the contribution guideline.  [here](https://github.com/MartinsOnuoha/countriesNowAPI/blob/master/docs/contributing.md)

Great! I'll be assigning this issue to @deepank120896 
@ryzbaka there's another issue [here](https://github.com/MartinsOnuoha/countriesNowAPI/issues/38), would you like to work on it?

**Comment by xarrijorge** [comment]
Is this still opened? If not, I would like to take a shot at it.

**Comment by MartinsOnuoha** [comment]
@deepank120896 @ryzbaka 


> Is this still opened? If not, I would like to take a shot at it.

@xarrijorge this issue is closed now, @ryzbaka raised a PR for it
