### ISSUE TITLE
add endpoint to get cities within a state.

### ISSUE THREAD

**Issue by MartinsOnuoha** [MartinsOnuoha/countriesNowAPI#38]
Within the `./model/countriesStateCity.js` Files you'll find countries, their respective states, and cities within that state.

The goal is to be able to get all the cities within a state.
For example, given this data:
```
{
      "id": 1,
      "name": "Afghanistan",
      "iso3": "AFG",
      "iso2": "AF",
      "phone_code": "93",
      "capital": "Kabul",
      "currency": "AFN",
      "states": [
          {
              "id": 3901,
              "name": "Badakhshan",
              "state_code": "BDS",
              "cities": [
                  {
                      "id": 52,
                      "name": "Ashkāsham",
                      "latitude": "36.68333000",
                      "longitude": "71.53333000"
                  },
                  {
                      "id": 68,
                      "name": "Fayzabad",
                      "latitude": "37.11664000",
                      "longitude": "70.58002000"
                  },
                  {
                      "id": 78,
                      "name": "Jurm",
                      "latitude": "36.86477000",
                      "longitude": "70.83421000"
                  },
                  {
                      "id": 84,
                      "name": "Khandūd",
                      "latitude": "36.95127000",
                      "longitude": "72.31800000"
                  },
                  {
                      "id": 115,
                      "name": "Rāghistān",
                      "latitude": "37.66079000",
                      "longitude": "70.67346000"
                  },
                  {
                      "id": 131,
                      "name": "Wākhān",
                      "latitude": "37.05710000",
                      "longitude": "73.34928000"
                  }
              ]
          }
```
----------

 We need to be able to get the cities within "Badakhshan" by sending a `POST` request to the `/state/cities` endpoint with this payload: 
```json
{
   "state": "Badakhshan"
}
```

**Comment by anuragphadnis** [comment]
I beleive that using get endpoints for fetching data would be better. I would suggest an end point like this.
`GET /country/{name}/state/{name}/cities`
Let me know your thoughts.

**Comment by PaulEvans8669** [comment]
Hello @MartinsOnuoha. Can I work on this?
According to your example, is this what you want the route to return?
```js
"cities": [
                  {
                      "id": 52,
                      "name": "Ashkāsham",
                      "latitude": "36.68333000",
                      "longitude": "71.53333000"
                  },
                  {
                      "id": 68,
                      "name": "Fayzabad",
                      "latitude": "37.11664000",
                      "longitude": "70.58002000"
                  },
                  {
                      "id": 78,
                      "name": "Jurm",
                      "latitude": "36.86477000",
                      "longitude": "70.83421000"
                  },
                  {
                      "id": 84,
                      "name": "Khandūd",
                      "latitude": "36.95127000",
                      "longitude": "72.31800000"
                  },
                  {
                      "id": 115,
                      "name": "Rāghistān",
                      "latitude": "37.66079000",
                      "longitude": "70.67346000"
                  },
                  {
                      "id": 131,
                      "name": "Wākhān",
                      "latitude": "37.05710000",
                      "longitude": "73.34928000"
                  }
              ]
```

Thank you.

**Comment by MartinsOnuoha** [comment]
> I believe that using get endpoints for fetching data would be better. I would suggest an endpoint like this.
> `GET /country/{name}/state/{name}/cities`
> In case such endpoints break the consistency within the application then I believe the payload should also contain the country name, also using city key and sending state as value is not appropriate. I would suggest such a payload.

@anuragphadnis  This endpoint format `GET /country/{name}/state/{name}/cities` would have been ideal if we were using IDs for the countries and the states, In that case, we'd make a GET request to `/country/{id}/state/{id}/cities`, however, we're not using this format because of the inconsistency of the data we have and they don't have IDs.

> {
>     "country": "Afghanistan",
>     "state": "Badakhshan"
> 
> }

Yes, you're right, adding the country to the payload does help streamline the search,

> also using city key and sending state as value is not appropriate
I corrected my previous comment, it's supposed to be a state key, not a city.

**Comment by MartinsOnuoha** [comment]
> Hello @MartinsOnuoha. Can I work on this?
> According to your example, is this what you want the route to return?
> 
> ```js
> "cities": [
>                   {
>                       "id": 52,
>                       "name": "Ashkāsham",
>                       "latitude": "36.68333000",
>                       "longitude": "71.53333000"
>                   },
>                   {
>                       "id": 68,
>                       "name": "Fayzabad",
>                       "latitude": "37.11664000",
>                       "longitude": "70.58002000"
>                   },
>                   {
>                       "id": 78,
>                       "name": "Jurm",
>                       "latitude": "36.86477000",
>                       "longitude": "70.83421000"
>                   },
>                   {
>                       "id": 84,
>                       "name": "Khandūd",
>                       "latitude": "36.95127000",
>                       "longitude": "72.31800000"
>                   },
>                   {
>                       "id": 115,
>                       "name": "Rāghistān",
>                       "latitude": "37.66079000",
>                       "longitude": "70.67346000"
>                   },
>                   {
>                       "id": 131,
>                       "name": "Wākhān",
>                       "latitude": "37.05710000",
>                       "longitude": "73.34928000"
>                   }
>               ]
> ```
> 
> Moreover, what should happen if a state name exists multiple time? e.g. `Saint George Parish`
> 
> Thank you.

@PaulEvans8669 Sure, the response from this endpoint would look something like this.

```json
{
  "error": false,
  "msg": "cities in STATE_NAME retrieved",
  "data": [
    "Khandūd",
    "Rāghistān",
    "Jurm",
    "Abraka",
    "Wākhān",
     ...
   ]
 }
```

**Comment by anuragphadnis** [comment]
> 
> 
> > I believe that using get endpoints for fetching data would be better. I would suggest an endpoint like this.
> > `GET /country/{name}/state/{name}/cities`
> > In case such endpoints break the consistency within the application then I believe the payload should also contain the country name, also using city key and sending state as value is not appropriate. I would suggest such a payload.
> 
> @anuragphadnis This endpoint format `GET /country/{name}/state/{name}/cities` would have been ideal if we were using IDs for the countries and the states, In that case, we'd make a GET request to `/country/{id}/state/{id}/cities`, however, we're not using this format because of the inconsistency of the data we have and they don't have IDs.
> 
> > {
> > "country": "Afghanistan",
> > "state": "Badakhshan"
> > }
> 
> Yes, you're right, adding the country to the payload does help streamline the search, there's an existing endpoint that gets all the cities in a country by sending this payload:
> 
> ```json
> {
>   "country": "Nigeria"
> }
> ```
> 
> > also using city key and sending state as value is not appropriate
> 
> I corrected my previous comment, it's supposed to be a state key, not a city.

Okay, @MartinsOnuoha. I would like to work on it, I will use payload with both country and state. Is it fine?

**Comment by PaulEvans8669** [comment]
Hi again @MartinsOnuoha, issue is very clear and I'd highly appreciate working on this.

**Comment by anuragphadnis** [comment]
@MartinsOnuoha 
I have created a PR for this issue #40, kindly review the changes.

**Comment by MartinsOnuoha** [comment]
> @MartinsOnuoha
> I have created a PR for this issue #40, kindly review the changes.

Hey, @anuragphadnis I checked your PR the builds are failing, I think it has to do with the tests.

**Comment by johnexzy** [comment]
I missed it.
