### ISSUE TITLE
Inconsistent "state" suffix in states

### ISSUE THREAD

**Issue by johnexzy** [MartinsOnuoha/countriesNowAPI#42]
When sending a POST request to `/state/cities`, the payload looks like
```
{
   "country" : "Nigeria",
   "state" : "Abia State"
}
```
But not all states have the "state" suffix. In other words, payload such as
```
{
   "country" : "Nigeria",
   "state" : "Abia"
}
```
 returns 404

**Comment by MartinsOnuoha** [comment]
@johnexzy Thanks for spotting this, would you be able to raise a PR for this issue?
