### ISSUE TITLE
some countries has no cites 

### ISSUE THREAD

**Issue by Kenan-Hussein** [MartinsOnuoha/countriesNowAPI#48]
Using https://countriesnow.space/api/v0.1/countries/positions
return some countries **name** in a different way when using this : 
https://countriesnow.space/api/v0.1/countries/info?returns=name

**Example:** 
/positions response: syria as "Syrian Arab Republic"
/info?returns=name response: "Syria"

Using "Syrian Arab Republic" as post request to get its cities return nothing, but when using "Syria" it works, the problem I need to use positions to get lat and long also to get a country name to get it cities.

I noticed there are some other countries that have the same issue.

**Comment by MartinsOnuoha** [comment]
Hi, @Kenan-Hussein I think I understand your issues, this is happening because of the difference in the data source, do you think you can help identify any other country with this problem?

**Comment by Kenan-Hussein** [comment]
@MartinsOnuoha Well.. that took some time but glad to help 

Here is your list:

Syrian Arab Republic
Brunei Darussalam
British Indian Ocean Territory
Bouvet Island
Cape Verde
Christmas Island
Cocos (Keeling) Islands
Cook Islands
Falkland Islands (Malvinas)
French Guiana
Gibraltar
Guernsey
Heard Island and McDonald Islands
Holy See (Vatican City State)
Jersey
Lao People's Democratic Republic
Macao
Marshall Islands
Monaco
Montserrat
Myanmar
Nauru
Niger
Niue
Norfolk Island
Northern Mariana Islands
Palau
Pitcairn
Saint Kitts and Nevis
Réunion
Saint Lucia
Saint Pierre and Miquelon
Saint Vincent and the Grenadines
Sao Tome and Principe
Sierra Leone
Serbia
South Georgia and the South Sandwich Islands
Tajikistan
Timor-Leste
Tokelau
Tuvalu
Turks and Caicos Islands
United States Minor Outlying Islands
Wallis and Futuna
Viet Nam

**Comment by MartinsOnuoha** [comment]
Thanks a lot @Kenan-Hussein , I'll get to work on fixing up these data, and raise a PR for it

**Comment by Kenan-Hussein** [comment]
still not working can you please fix Syrian Arab Republic at less please

**Comment by MartinsOnuoha** [comment]
Hey @Kenan-Hussein apologies, I've been trying to validate some of these countries and making sure their names haven't changed, yet, expect a fix today.

**Comment by MartinsOnuoha** [comment]
@Kenan-Hussein 
Some of these places with the issue are mostly archipelagos and less populated areas and have no cities, so you might still get an empty array for those requests, but the "Not found error" and other issues related to the listed countries should be resolved now.
