### ISSUE TITLE
[bug][missing data] The Netherlands result in an internal server error

### ISSUE THREAD

**Issue by Zeus3hd** [MartinsOnuoha/countriesNowAPI#63]
Hello

I'm facing issues with `The Netherlands`.

these endpoints return `404 country not found`

POST `https://countriesnow.space/api/v0.1/countries/cities`

```
{
	"country": "Netherlands"
}
```

I've tried different variations of the country's name in addition to its informal name `holland` with different casing.

it's either 404 not found or internal server error.

**Comment by MartinsOnuoha** [comment]
Hi @Zeus3hd, I just checked and noticed this issue, I'm raising a fix for it right now.
