### ISSUE TITLE
Incorrect states

### ISSUE THREAD

**Issue by CountriesFix** [MartinsOnuoha/countriesNowAPI#65]
Hi,

The following states are in the wrong location.
- Bonaire
- Saba
- Sint Eustatius

They currently fall under **The Netherlands (NL)**, but they're supposed to be under **Netherlands Antilles (AN)**.

Tried pushing and doing a pull request, but I'm receiving some errors.
Needs to be corrected in the following files.

`countriesStateCity.js` and `countriesAndState.js`

**Comment by peter81git** [comment]
Also Chicago is present as being part of Mexico.

**Comment by MartinsOnuoha** [comment]
Hey @CountriesFix what challenges did you face when trying to raise a PR?

**Comment by MartinsOnuoha** [comment]
@peter81git do you think you can raise a PR for that?
