### ISSUE TITLE
Endpoint doesn't work

### ISSUE THREAD

**Issue by dawidkasz** [MartinsOnuoha/countriesNowAPI#72]
Hi,
This endpoint: https://countriesnow.space/api/v0.1/countries/population/filter
returns an internal server error when queried with
{"country": "United Kingdom"} data.

**Comment by MartinsOnuoha** [comment]
Hello, @dawidkasz, This isn't the correct payload to use for this endpoint. Please see [here](https://documenter.getpostman.com/view/1134062/T1LJjU52) for the correct usage. 
The Postman collection should guide you on how to use the population endpoint. 

<img width="471" alt="CleanShot 2021-09-28 at 10 44 01@2x" src="https://user-images.githubusercontent.com/29035007/135063884-ef3886c8-7ada-4fe1-a14d-349abb32049d.png">

I'll be closing this issue now.
