### ISSUE TITLE
Where is the data being sourced from?

### ISSUE THREAD

**Issue by oberek** [MartinsOnuoha/countriesNowAPI#80]
Hello!
First of all, thank you so much for this API! It's very useful 🥇 
Second of all, where are you sourcing your city information from? I'm assuming that it's census records, but I'm genuinely curious.

**Comment by MartinsOnuoha** [comment]
Hi 👋 , So currently the data is aggregated from the [file system ](https://github.com/MartinsOnuoha/countriesNowAPI/tree/master/model) and [datahub](https://github.com/MartinsOnuoha/countriesNowAPI/blob/master/controllers/dataHub/index.js), datahub mostly provides the census related data, however, the response from data hub isn't the easier to work with, which is where countries now come in the clean it up and put it all in one uniform response. 
We're looking at finding more ways to make data collation more robust, this project is also a [data source](https://github.com/dr5hn/countries-states-cities-database)
