### ISSUE TITLE
Some countries inconsistent and missing

### ISSUE THREAD

**Issue by henryhuangh** [MartinsOnuoha/countriesNowAPI#81]
Data retrieved from endpoints inconsistent, this can lead to conflicts and inability to retrieve data across endpoints. If a country is retrieved from `/countries/positions`, that same country should be valid to retrieve data from `/countries/cities`

For instance in the endpoint
`/countries/positions`
**South Korea** is referred to as **Korea, Republic of**

`/countries`
**South Korea** becomes **Korea South**

Same inconsistency problem with **Ivory Coast**: in `/countries/capital` it is **Ivory Coast** but in `/countries/positions` it is **Cote d'Ivoire.**
Both **Ivory Coast** and **Cote d'Ivoire** returns **`country not found`** when querying `/countries/cities`

**Comment by MartinsOnuoha** [comment]
Hi Henry, thanks for pointing this out, yes this is something we're making fixes for since we're aggregating data from multiple data sources to make sure we have as much data as possible.

would you like to look into creating a fix for this, or, can you help identify other countries with the same issue? and I'll raise a fix for this

**Comment by henryhuangh** [comment]
Hi Martins, It would be great if you can look into creating a fix and I can be a second pair of eyes. Unfortunately I cannot work on a fix directly as I am tied with other developments for my company. But I can certainly be your second pair of eyes.

Also, I found 2 Botwanas in `countriesAndCities.js`.

**Comment by MartinsOnuoha** [comment]
Hi @henryhuangh, be rest assured that I'm working on a fix for as much as I can find.

**Comment by MartinsOnuoha** [comment]
@henryhuangh have a look at the linked MR, let me know if it looks good.
