### ISSUE TITLE
Multilangual names

### ISSUE THREAD

**Issue by SaraShoukry** [MartinsOnuoha/countriesNowAPI#82]
Thanks for the great work
Can you guide me to create an Arabic version for this?

**Comment by MartinsOnuoha** [comment]
Hi @SaraShoukry, Sure I can do that.
Which part of the API would you like to translate? The documentation? or the responses?

**Comment by SaraShoukry** [comment]
@MartinsOnuoha  The countries, states & cities

**Comment by MartinsOnuoha** [comment]
Hi @SaraShoukry , alright, can you show a sample of what the arabic response would look like?
For example. This is the English response for a single country and a flag:

```
{
  "error": false,
  "msg": "country and flag retrieved",
  "data": {
    "name": "Nigeria",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg"
  }
}
```

can you show me what an arabic version of this would look like?

**Comment by vijaynk18** [comment]
@SaraShoukry Can you please provide the response in Arabic so that we can close this issue?

**Comment by MartinsOnuoha** [comment]
Hi @lpunderscore , Currently we do not have translations for the API, and yes the translation would have to be done manually for each state/provinces

**Comment by SaraShoukry** [comment]
sorry but i didn't complete the translation task

**Comment by MartinsOnuoha** [comment]
That's alright, let me know if you still want to do this, else we can close this issue.
