### ISSUE TITLE
Spain provinces issue

### ISSUE THREAD

**Issue by FANMixco** [MartinsOnuoha/countriesNowAPI#98]
There are three provinces in the States that I'd add as provinces since there is a mix between the Communities (States in our case) and the provinces. In order to minimize the double effort, I'd add the word province at the end to the following places:

- Gipuzkoa
- Biscay
- Araba Álava

Thanks for your great work!

**Comment by MartinsOnuoha** [comment]
Hi Mixco, awesome, I think we can have a quick fix for this immediately. Thanks.

**Comment by MartinsOnuoha** [comment]
Hey @FANMixco we have an open PR for this issue, you can have a look before I merge it.
